version: '3'

services: 
  app:
    build: .
    container_name: fin-api_app
    ports: 
      - 3301:3000
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes: 
     - .:/home/node/app
    depends_on: 
      - db
    
  db:
    build: ./.docker/mysql
    container_name: fin-api_db
    ports: 
      - 3302:3306
    restart: always
    tty: true
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=fin-api
      - MYSQL_PASSWORD=fin-api-123